# Generated by Django 4.2 on 2023-11-20 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_school_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('file_upload', models.FileField(upload_to='ads/')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schoolads', to='core.school')),
            ],
        ),
    ]
