# Generated by Django 4.2 on 2023-11-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_schoolads'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolads',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
