# Generated by Django 4.2.7 on 2023-12-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooljoining',
            name='show_file',
            field=models.BooleanField(default=True),
        ),
    ]
