# Generated by Django 4.2.7 on 2023-12-09 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_schoolcalender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchoolCalender',
            new_name='SchoolCalendar',
        ),
    ]
