# Generated by Django 4.2.7 on 2023-12-09 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_schoolcalender_schoolcalendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolcalendar',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schoolacalendar', to='core.school'),
        ),
    ]
