# Generated by Django 4.2.7 on 2023-12-12 16:14

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_schoolcalendar_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schoolvideos', to='core.school')),
            ],
        ),
    ]
